### PR TITLE
General updating

### PR DESCRIPTION
**Pull request by mor1**
debian 7.8.0 has a problem with 0install currently but the rest seems to work.

### CODE REVIEW

**Comment by avsm** [comment]
Nice!

**Comment by mor1** [comment]
adding xenserver support now, and will also pull in magnus' blog post network config

**Comment by avsm** [comment]
It's probably time to merge this...

**Comment by mor1** [comment]
Yes will try and finish over weekend. Yesterday taken out by extended
Yosemite upgrade. Bad Apple. Naughty Apple.

**Comment by mor1** [comment]
ok-- merging this, though i haven't finished network config yet. but the basics seem to work, from box creation through to installation of mirage.

**Comment by avsm** [comment]
Tell devel list as well?

**Comment by mor1** [comment]
Will do

**Pull request merged**
